[ENG-7507] - Update ReadMe
Neuro-ID/neuroid-reactnative-sdk pull request #152
Opened 2024-03-18 21:10 UTC by kevinsites

Note - Sonar does not work on the React-Native repo currently, this is still being investigated

2024-03-18 23:13 UTC, cometman requested changes

2024-03-18 23:13 UTC, cometman commented on README.md
> +NeuroID's React-Native Mobile SDK makes it simple to embed behavioral analytics inside your mobile application. With a few lines of code, you can connect your app with the NeuroID platform and make i
React Native should not be hyphenated. Yes this is the most pedantic review, sorry LOL :( Lots of instances below, I will do you the grace of not commenting on each one...

2024-03-18 23:13 UTC, cometman commented on README.md
> +The NeuroID React-Native Mobile SDK is provided under an [MIT License](LICENSE).
No idea if this is worth calling out, but the other SDK's / Javascript dont have a license mentioned in the readme that I saw.

2024-03-20 18:22 UTC, priya-xavier approved these changes

2024-03-20 18:26 UTC, quacke-nid approved these changes

2024-03-20 19:18 UTC, cometman approved these changes

2024-03-21 21:02 UTC, merged